### ISSUE TITLE
Язык Make в задаче Tournament Tree Mutex

### ISSUE THREAD

**Issue by shevkunov** [dbeliakov/mipt-algo-2016#2]
При сдаче задачи A (16 сентября) доступен только один язык - Make. При сдаче компилируемого кода на C++ получаю такой вывод c вердиктом CE:
stdout:

stderr:
make: **\* No targets specified and no makefile found.  Stop.

**Comment by Ya-Egor** [comment]
Была ошибка в проверялке (недозалил файлы). Поправил, отправленные решения пересудил. К сожалению, успешных решений не обнаружено :(. Проверяйте логи компилятора, если в них что-то непонятно - задавайте вопросы.

**Comment by IlRomanenko** [comment]
При отправке задачи A для обновленного компилятора получаю следующий лог :
stdout:
'/temp/compiling/source' cannot be extracted via extract ()
TMP=$(pwd) clang++ -std=c++14 -pthreads -O3 -g -Wall -Wextra -Werror -o ./solution *.cpp


stderr:
main.cpp:2:10: fatal error: 'tree_mutex.h' file not found
#include "tree_mutex.h"
         ^
1 error generated.
make: *** [build] Error 1

Нужно ли дополнительно описывать что-то в отправляемой посылке (код - обычный header файл)?
