### ISSUE TITLE
Лог компиляции в задаче Tournament Tree Mutex

### ISSUE THREAD

**Issue by IlRomanenko** [dbeliakov/mipt-algo-2016#3]
При отправке задачи A для обновленного компилятора получаю следующий лог, который выглядит как ошибка на стороне сервера :
stdout:
'/temp/compiling/source' cannot be extracted via extract ()
TMP=$(pwd) clang++ -std=c++14 -pthreads -O3 -g -Wall -Wextra -Werror -o ./solution *.cpp

stderr:
main.cpp:2:10: fatal error: 'tree_mutex.h' file not found
# include "tree_mutex.h"

^
1 error generated.
make: **\* [build] Error 1

Нужно ли дополнительно описывать что-то в отправляемой посылке (код - обычный header файл)?
P.S. Начало решения выглядит след. образом :
# pragma once

class tree_mutex {
...

**Comment by shevkunov** [comment]
Есть гипотеза, что файл должен называться "tree_mutex.h", ибо у меня так это работает.

**Comment by IlRomanenko** [comment]
Да, именно так. Еще, кажется, это была посылка, когда была возможность отправить код, набранный прямо в браузере. К слову, нигде не написано, что файл с отправляемым решением должен называться именно так.
