### ISSUE TITLE
Linker command failed

### ISSUE THREAD

**Issue by IlRomanenko** [dbeliakov/mipt-algo-2016#7]
При использовании atomic<__int128_t> в задаче Lock-Free Queue (Thread Sanitizer) решение получает OK, в то время как в задаче Lock-Free Queue (Address Sanitizer) получается ошибка линковки. Вывод приведен ниже.
> stdout:
> '/temp/compiling/lock_free_queue.h' cannot be extracted via extract ()
> TMP=$(pwd) clang++ -std=c++14 -fsanitize=address -pthreads -O3 -g -Wall -Wextra -Werror -o ./solution *.cpp
> 
> 
> stderr:
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::store(__int128, std::memory_order)':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:199: undefined reference to `__sync_lock_test_and_set_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:199: undefined reference to `__sync_lock_test_and_set_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:199: undefined reference to `__sync_lock_test_and_set_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::load(std::memory_order) const':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::operator __int128() const':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::exchange(__int128, std::memory_order)':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:225: undefined reference to `__sync_lock_test_and_set_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::load(std::memory_order) const':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::operator __int128() const':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::exchange(__int128, std::memory_order)':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:225: undefined reference to `__sync_lock_test_and_set_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::load(std::memory_order) const':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::compare_exchange_strong(__int128&, __int128, std::memory_order, std::memory_order)':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:268: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o: In function `std::atomic<__int128>::load(std::memory_order) const':
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_16'
> /temp/compiling/main-594428.o:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:268: more undefined references to `__sync_val_compare_and_swap_16' follow
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [build] Error 1

**Comment by Ya-Egor** [comment]
А что говорит atomic<__int128_t>::is_lock_free() в Lock-Free Queue (Thread Sanitizer)?

**Comment by IlRomanenko** [comment]
В конструкторе написан assert(head.is_lock_free()); где head -> atomic<__int128_t> head;

**Comment by Ya-Egor** [comment]
Пока нашёл описание похожего бага: https://llvm.org/bugs/show_bug.cgi?id=19750
Вкратце: похоже, что библиотека address sanitizer была собрана с другими настройками clang, и в ней вызовы для 16-байтных атомарных операций сделаны через вызов библиотечных функций. А clang, который используется при компиляции решения, подставляет в места вызова машинные инструкции, и реализаций этих библиотечных функций у него нет (они все inline). Тогда получается, что это должны править админы Я-контеста (пересобрать address sanitizer). А это будет явно небыстро. 
Но, по условию, решение задачи B (Lock-Free Queue (Thread Sanitizer)) так же является решением задачи А (Address Sanitizer), так что ничего страшного.
