### ISSUE TITLE
Error while loading shared libraries!

### ISSUE THREAD

**Issue by eshlykov** [dbeliakov/mipt-algo-2016#8]
Моя программа в задаче Addresss Sanitizer получает RE 1 с сообщением:
```
./solution: error while loading shared libraries: libclang_rt.asan-x86_64.so: cannot open shared object file: No such file or directory
```
Посылка с ID 3527306, например.

**Comment by Ya-Egor** [comment]
Поправил. Теперь ругается по делу:
==10==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1600000 byte(s) in 100000 object(s) allocated from:
    #0 0x4debfb  (/temp/executing/solution+0x4debfb)
    #1 0x4e54d8  (/temp/executing/solution+0x4e54d8)
    #2 0x4e3d77  (/temp/executing/solution+0x4e3d77)
    #3 0x2b3957e1ab0f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb7b0f)

Direct leak of 144 byte(s) in 6 object(s) allocated from:
    #0 0x4debfb  (/temp/executing/solution+0x4debfb)
    #1 0x4e552b  (/temp/executing/solution+0x4e552b)
    #2 0x4e3d77  (/temp/executing/solution+0x4e3d77)
    #3 0x2b3957e1ab0f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb7b0f)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4debfb  (/te

File is too long to be displayed fully

**Comment by jewgeni-r** [comment]
А можно в настройки прописать что-то типа `-g`, чтобы показывалось, где именно утечка? Искать утечку 24-х байтов в одной аллокации по всей программе - как иголку в стоге сена. :)

**Comment by Ya-Egor** [comment]
Уже прописано, но это не поможет. Нужно указать путь к внешней утилите, переводящей позиции в бинарнике в красивые позиции в исходном коде. А это опять надо к админам контеста обращаться.
AddressSanitizer uses an external symbolizer to print files and line numbers in reports. Make sure that llvm-symbolizer binary is in PATH, or set environment variable MSAN_SYMBOLIZER_PATH to point to it.

**Comment by jewgeni-r** [comment]
А есть ссылка на тестирующий код? Конкретно интересует тот файл, который выводит сообщения вида:
```
Starting MP/MC test...
Num producers = 1
Num consumers = 1
Num items = 100000
Joining producer threads...
Joining consumer threads...
Num consumed items: 100000
Test completed
```
В некоторых задачах раньше была ссылка на GitHub Р. Липовского, но, кажется, для этой задачи там нет нужного файла.
