### ISSUE TITLE
ошибка компиляции lock-free task A

### ISSUE THREAD

**Issue by nina-vishnyakova** [dbeliakov/mipt-algo-2016#9]
stdout:
'/temp/compiling/lock_free_queue.h' cannot be extracted via extract ()
TMP=$(pwd) clang++ -std=c++14 -fsanitize=address -pthreads -O3 -g -Wall -Wextra -Werror -shared-libasan -o ./solution *.cpp

stderr:
In file included from main.cpp:1:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:167:7: error: exception specification of explicitly defaulted default constructor does not match the calculated one
      atomic() noexcept = default;
      ^
./lock_free_queue.h:125:31: note: in instantiation of template class 'std::atomic<Tpointer<Value> >' requested here
    std::atomic<Tpointer<T> > head;
                              ^
./lock_free_queue.h:130:32: note: in instantiation of template class 'simple_lock_free_queue<Value>' requested here
class lock_free_queue : public simple_lock_free_queue<T>
                               ^
main.cpp:27:15: note: in instantiation of template class 'lock_free_queue<Value>' requested here
        Queue queue;
              ^
main.cpp:74:32: note: in instantiation of template class 'QueueTests::testing_context<lock_free_queue<Value> >' requested here
        testing_context<Queue> ctx{opts};
                               ^
In file included from main.cpp:1:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/atomic:167:7: error: exception specification of explicitly defaulted default constructor does not match the calculated one
      atomic() noexcept = default;
      ^
./lock_free_queue.h:125:31: note: in instantiation of template class 'std::atomic<Tpointer<Tpointer<Value> > >' requested here
    std::atomic<Tpointer<T> > head;
                              ^
./lock_free_queue.h:151:42: note: in instantiation of template class 'simple_lock_free_queue<Tpointer<Value> >' requested here
    simple_lock_free_queue<Tpointer<T> > del;
                                         ^
main.cpp:27:15: note: in instantiation of template class 'lock_free_queue<Value>' requested here
        Queue queue;
              ^
main.cpp:74:32: note: in instantiation of template class 'QueueTests::testing_context<lock_free_queue<Value> >' requested here
        testing_context<Queue> ctx{opts};
                               ^
2 errors generated.
make: *** [build] Error 1

**Comment by Ya-Egor** [comment]
По первой проблеме - спецификация требует, чтобы конструктор atomic не бросал исключения. Но твой класс может бросать исключения в конструкторе (как минимум потому, что ты явно не указала обратное, объявив его noexcept). По второй проблеме - внимательно прочитай условие на интерфейс класса lock_free_queue

**Comment by nina-vishnyakova** [comment]
Я дописала noexcept для конструктора и, потом, вообще для всего, но это не помогло
